function non_falls_data = get_non_falls()
    non_falls_data = [];
    non_falls = [...
        '3ITB1D'; ...
        '3ATF2D'; ...
        '3NNC4A'; ...
        '3NNC4B'; ...
        '3NNC4C'; ...
        '3NNC4D'];
    data = get_data_file(non_falls, 'Sujet_3');
    non_falls_data = [non_falls_data; data];
    
    non_falls = [...
        '5ITB1D'; ...
        '5ATF2D'; ...
        '5NNC4A'; ...
        '5NNC4B'; ...
        '5NNC4C'; ...
        '5NNC4D'];
    data = get_data_file(non_falls, 'Sujet_5');
    non_falls_data = [non_falls_data; data];